import type { Metadata } from "next";
import { Lora, Cormorant_Garamond, Nunito } from "next/font/google";
import "./globals.scss";
import { CSSProperties } from "react";
import Header from "./components/header/Header";

const lora = Lora({ subsets: ["latin"] });
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={lora.className}
        style={
          {
            "--fontMain": lora.style.fontFamily,
            "--fontSecondary": cormorant.style.fontFamily,
            "--fontAlt": nunito.style.fontFamily,
          } as CSSProperties
        }
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
